### ISSUE TITLE
Research online vs offline dictionary API options and create a dictionary fir the app 

### ISSUE THREAD

**Issue by DillyPickly** [cse442-spring-2020-offering/cse442-semester-project-team10#10]
Do we want to just use a mobile api or create an offline one in the app.

Test: dictionary.json file created in src/data/ directory

**Comment by DillyPickly** [comment]
Decided on using a JSON file to store the dictionary.

**Comment by ericliu1998** [comment]
Acceptance Test
dictionary.json file created in src/data/ directory
