### ISSUE TITLE
Make sure that that the best words are calculated with their correct scores

### ISSUE THREAD

**Issue by DillyPickly** [cse442-spring-2020-offering/cse442-semester-project-team10#27]

**Comment by ericliu1998** [comment]
Acceptance test
when the app opens
1) Go to search bar in the input section and search the word “NOCTURNAL”. The number before  “NOCTURNAL” which is the score = 2+1+4+1+2+1+2+1+2=16.

2)  All the words discovered are subsets of the letters in nocturnal.
