### ISSUE TITLE
Research pros and cons of react native vs android studio

### ISSUE THREAD

**Issue by Calkulate** [cse442-spring-2020-offering/cse442-semester-project-team10#4]
React Native allows us to have mobile development for ios and android.

**Comment by Calkulate** [comment]
React Native can save us time as we do not need to develop two separate apps and have a large amount of packages that we can use.

**Comment by Calkulate** [comment]
Android studio has testing in its own ide which saves time to see changes in the code and how it affects the app.

**Comment by DillyPickly** [comment]
We decided to go with React Native as it can be ported to iOS easily even though none of us have macs so we cannot put the app of our phones. React Native also uses any emulator so Android Studios works with react native.
